#!/usr/bin/env python
from source.scraper import ImageScraper
from source.sender import Sender

def main():
    scraper = ImageScraper()
    sender = Sender()
    scraper.scrapeImages()
    print(f"\033[92mStarting sender\033[0m")
    sender.run()

if __name__ == "__main__":
    main()